name: instagram_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.0.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  provider: ^6.0.1
  uuid: ^3.0.5
  random_avatar: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/ic_instagram.svg
